version: '3'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - prometheus
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.logind'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - prometheus
      - grafana
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - grafana
      - prometheus
      - zabbix
      - db
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-server-pgsql
    restart: unless-stopped
    networks:
      - zabbix
      - db
    environment:
      - DB_SERVER_HOST=db
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql
    container_name: zabbix-web-nginx-pgsql
    restart: unless-stopped
    networks:
      - zabbix
      - db
    env_file:
      - ./.env
    ports:
      - "80:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    restart: unless-stopped
    networks:
      - zabbix
      - db
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  db:
    image: postgres:14-alpine
    container_name: zabbix-db
    stop_grace_period: 1m
    ports:
      - "5432:5432"
    networks:
      - zabbix
      - grafana
    environment:
      - TZ=UTC
    env_file:
      - ./.env
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  prometheus_data:
  grafana_data:
  zabbix-db:

networks:
  prometheus:
  grafana:
  zabbix:
  db: