groups:
- name: ./rules.conf
  rules:

  # heartbeat alert
  - alert: Heartbeat
    expr: vector(1)
    labels:
      event: "Heartbeat"
      instance: "prometheus"
      monitor: "prometheus"
      severity: "major"
      timeout: "120"
    annotations:
      summary: "Heartbeat from prometheus"
      description: "Heartbeat from from prometheus"

  # service availability alert
  - alert: service_down
    expr: up == 0
    labels:
      service: Platform
      severity: major
      correlate: service_up,service_down
    annotations:
      description: Service {{ $labels.instance }} is unavailable.
      value: DOWN ({{ $value }})
      runbook: http://wiki.alerta.io/RunBook/{app}/Event/{alertname}

  # system load alert
  - alert: high_load
    expr: node_load1 > 0.5
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} is under high load.'
      summary: Instance {{ $labels.instance }} under high load
      value: '{{ $value }}'

  # disk space alert (with resource=<instance>:<mountpoint> event=disk_space
  - alert: disk_space
    expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 5
    labels:
      instance: '{{ $labels.instance }}:{{ $labels.mountpoint }}'
    annotations:
      value: '{{ humanize $value }}%'

  # disk space alert (with resource=<instance> event=disk_util:<mountpoint>
  - alert: disk_util
    expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 5
    labels:
      instance: '{{ $labels.instance }}'
      event: '{alertname}:{{ $labels.mountpoint }}'
    annotations:
      value: '{{ humanize $value }}%'

  # This alert fires when a Windows service with automatic start mode stops running.
  - alert: ServiceStoppedAutoStart
    expr: windows_service_state{state="stopped"} * on(name) group_left windows_service_start_mode{start_mode="auto"} == 1
    labels:
      severity: high
    annotations:
      summary: "Service {{ $labels.name }} is stopped but has auto start mode"
      description: "{{ $labels.name }} service is stopped but has an automatic start mode."
