apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true

- name: db-PostgreSQL
  type: postgres
  access: proxy
  url: db
  database: zabbix
  user: zabbix
  editable: true
  secureJsonData:
    password: zabbix
  jsonData:
    database: grafana
    sslmode: 'disable' # disable/require/verify-ca/verify-full
    maxOpenConns: 100 # Grafana v5.4+
    maxIdleConns: 100 # Grafana v5.4+
    maxIdleConnsAuto: true # Grafana v9.5.1+
    connMaxLifetime: 14400 # Grafana v5.4+
    timescaledb: false
